### ISSUE TITLE
TagWriters are never stopped

### ISSUE THREAD

**Issue by TrustNoOne** [akka/akka-persistence-cassandra#320] opened 2018-02-14 07:50 UTC
As far as i know, [TagWriters are never stopped](https://github.com/akka/akka-persistence-cassandra/blob/master/core/src/main/scala/akka/persistence/cassandra/journal/TagWriters.scala#L122). 

In some cases it could be desirable to design aggregate roots using multiple actors (in the same hierarchy maybe) for separation of concerns and tag them all using the same tag. I am actually doing this in production code, it should correspond to having an "unconfigured" tag in 0.50 so that it would end up in `tag1`.

I think `TagWriter`s should be stopped after an inactivity period to avoid leaks.

**Comment by chbatey** [comment] 2018-02-14 09:41
This is a good idea so we can support use cases with a lot of tags. 

We could also fix this by having a single tag writer actor rather than one per tag.

**Comment by TrustNoOne** [comment] 2018-02-16 13:49
The current `TagWriters` actor already receives all tagged events and forwards them to children, I guess a single actor would work fine instead of relying on timeouts.

On a different note, shouldn't this be a bug? It's a regression since this use case was supported before, I am actually using it so I cannot migrate any env to the new version until this is done

**Comment by chbatey** [comment] 2018-07-30 08:38
Sorry @TrustNoOne I missed your last comment. Yes I think this is a regression.

**Comment by brunogbv** [comment] 2019-08-15 19:57
Hi guys, this issue is affecting one of my microservices and I'd really like to help, but I'm not sure how. From what I've observed, TagWriters aren't being stopped and upon system restart they're all being recreated, which behaves like a persistent leak. The number of actors were measured via Kamon.

Also I've realized that there's a lot of issues related to tags open, but what is the reason for that? Should tags not be used or is it a technical detail related to Cassandra?

Thanks in advance and looking forward to contribute

**Comment by patriknw** [comment] 2019-08-16 13:14
I'll try to look into it next week.

**Comment by brunogbv** [comment] 2019-08-16 14:06
Thanks @patriknw, if I can be of assistance in any way just let me know.

**Comment by patriknw** [comment] 2019-08-19 12:56
@brunogbv I have implemented the stopping of idle tag writers in https://github.com/akka/akka-persistence-cassandra/pull/542. It would be great if you can try it out in your application. Would you be able to build a snapshot version from the branch in that PR?

**Comment by brunogbv** [comment] 2019-08-19 15:15
@patriknw Sure, today I'm busy at work but give me two days, I'll run the tests and post the results here.

**Comment by patriknw** [comment] 2019-08-19 15:49
thanks

**Comment by chbatey** [comment] 2019-10-29 17:09
Marking as small as the work is already done.

**Closed** 2020-01-20 09:22 UTC
Labels: bug, help wanted, size:s, t:events-by-tag
