### ISSUE TITLE
Read consistency level configuration value is ignored

### ISSUE THREAD

**Issue by kharole** [akka/akka-persistence-cassandra#185] opened 2017-04-11 13:51 UTC
Steps to repoduce
1. Set consistence levels as follows:
` write-consistency = "ONE"
  read-consistency = "ONE"`
2. connect to a single-node cassandra cluster and key space with replication factor 3
3. run a request that invokes persistent actor recovery
Expected: succesfull recovery
Actually: `(tried: /172.25.4.20:9042 (com.datastax.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)))`

Seems like read consistency configuration value for event journal is actually ignored.

**Comment by patriknw** [comment] 2017-04-12 06:46
Can you see which statement it fails on?

I know that it is not set on the statements for the `config` table. We should probably set it there also. 
https://github.com/akka/akka-persistence-cassandra/blob/master/src/main/scala/akka/persistence/cassandra/journal/CassandraStatements.scala#L193

BTW, using write-consistency = "ONE" read-consistency = "ONE" is a bad idea, but you might just be testing something.

**Comment by kharole** [comment] 2017-04-12 08:30
I totally realize that ONE is not the best idea. Turned out not an easy task to track it down to statement but seems it is selectHighestSequenceNr since I can see it is the first thing that fails on persistent actor recovery.

**Comment by patriknw** [comment] 2017-04-12 09:10
readConsistency is set on `preparedSelectHighestSequenceNr`.

I'm pretty sure it is the config table, via `initializePersistentConfig` which is done once when the session is created.

You should be able to confirm by setting property:
```
cassandra-journal.log-queries = on
```

and logback.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <target>System.out</target>
        <encoder>
            <pattern>%date{MM/dd HH:mm:ss} %-5level[%thread] %logger{1} - %m%n%xException</pattern>
        </encoder>
    </appender>

    <logger name="com.datastax.driver.core" level="DEBUG" />

    <root level="INFO">
        <appender-ref ref="CONSOLE"/>
    </root>

</configuration>
```

**Comment by kharole** [comment] 2017-04-14 09:26
It is on select from metadata

`2017-04-14 11:21:35,154 [DEBUG] from com.datastax.driver.core.RequestHandler in cluster1-nio-worker-1 - [1731733450-1] Error querying /172.25.4.20:9042 : com.datastax.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)
2017-04-14 11:21:35,158 [DEBUG] from com.datastax.driver.core.QueryLogger.ERROR in cluster1-nio-worker-1 - [cluster1] [/172.25.4.20:9042] Query error after 25 ms: [1 bound values] SELECT deleted_to FROM games.metadata WHERE
        persistence_id = ?;
com.datastax.driver.core.exceptions.UnavailableException: Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)
        at com.datastax.driver.core.exceptions.UnavailableException.copy(UnavailableException.java:128)
        at com.datastax.driver.core.Responses$Error.asException(Responses.java:114)
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:500)
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1012)
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:935)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
`

**Comment by patriknw** [comment] 2017-04-18 12:46
@kharole Sorry, but I can't reproduce that and in the source code the read consistency is set for that statement. I tried with a 3 node Cassandra cluster, replication-factor=3, write-consistency = "ONE" read-consistency = "ONE". Stopped 2 of the 3 nodes, and recovery (and other things) still works fine. Changed to QUORUM and then it fails.

Which version are you using?

Do you have a reproducer that you can share?

**Comment by VRanga000** [comment] 2017-04-27 20:50
Submitted a PR for this: https://github.com/akka/akka-persistence-cassandra/pull/199

**Comment by kharole** [comment] 2017-05-13 14:45
I've created brand new app with all the setting preserved (https://github.com/kharole/ConsistencyLevelRepro/) but was not able to reproduce the issue anymore. It reacts on consistency-level changes perfectly well. So was most probably my mistake. Sorry for disturbance and thanks for help.

**Comment by patriknw** [comment] 2017-05-15 11:35
thanks for the update, I don't mind incorporating @VRanga000 's PR anyway

**Comment by patriknw** [comment] 2017-11-27 09:19
Closing this without action, see motivation in https://github.com/akka/akka-persistence-cassandra/pull/199#issuecomment-347122177

**Closed by patriknw** 2017-11-27 09:19 UTC
