### ISSUE TITLE
No persisted events are replayed on recovery. `RecoveryCompleted` is received though

### ISSUE THREAD

**Issue by mkhudyakov** [akka/akka-persistence-cassandra#73] opened 2016-03-25 16:15 UTC
Please, see my comment on stackoverflow http://stackoverflow.com/questions/36223040/events-are-not-recovering-in-akka-2-4-0-persistence-cassandra-journal-plugin-0

**Comment by patriknw** [comment] 2016-03-27 19:48
It works fine for me. Please use Akka 2.4.2 and akka-persistence-cassandra 0.11

**Comment by mkhudyakov** [comment] 2016-03-27 20:47
Patrik, thanks for your answer. It looks like the problem is detected now.
I've updated akka to the version `2.4.2` and akka-persistence-cassandra to the version `0.11` and still had an issue, where the events were not replaying, though the `RecoveryCompleted` was received.

I thought then, that the issue could be in Cassandra version that I use. I use DSE 4.7 (where Cassandra version is `2.1.x`) and that time I was using the configuration `cassandra-2x-compat=on` for the plugin to be compatible. So the update of akka and plugin didn't help.

Then I tried another evrsion of Cassandra, that is the community edition one `3.4.0`, removed the `cassandra-2x-compat=on` configuration and now the events are being replayed.

Now it seems, like there is an issue related to the compatibility of plugin with cassandra `2.x`. There is no DSE release yet with Cassandra 3.x, that's why this fix is rather critical. Could you, please, take a look?

**Comment by patriknw** [comment] 2016-03-28 07:32
Do you see anything in the logs?
Did you try with a clean keyspace? Old schemas might need migrations.

**Comment by mkhudyakov** [comment] 2016-03-28 08:47
The logs on my side looks like there is no error. Here is the log, when the events are replayed (on Cassandra 3.x):
```
[DEBUG] [03/28/2016 11:18:06.167] [PersistentFsmPoc-akka.actor.default-dispatcher-25] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor] Retry request for shard [6] homes from coordinator at [Actor[akka://PersistentFsmPoc/system/sharding/transaction-actorCoordinator/singleton/coordinator#-1014771397]]. [1] buffered messages.
[DEBUG] [03/28/2016 11:18:06.170] [PersistentFsmPoc-cassandra-journal.default-dispatcher-20] [akka.serialization.Serialization(akka://PersistentFsmPoc)] Using serializer[akka.cluster.sharding.protobuf.ClusterShardingMessageSerializer] for message [akka.cluster.sharding.ShardCoordinator$Internal$ShardHomeAllocated]
[DEBUG] [03/28/2016 11:18:06.174] [PersistentFsmPoc-akka.actor.default-dispatcher-25] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actorCoordinator/singleton/coordinator] Shard [6] allocated at [Actor[akka://PersistentFsmPoc/system/sharding/transaction-actor#769956182]]
[DEBUG] [03/28/2016 11:18:06.174] [PersistentFsmPoc-akka.actor.default-dispatcher-17] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor] Host Shard [6] 
[DEBUG] [03/28/2016 11:18:06.176] [PersistentFsmPoc-akka.actor.default-dispatcher-17] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor] Starting shard [6] in region
[DEBUG] [03/28/2016 11:18:06.178] [PersistentFsmPoc-akka.actor.default-dispatcher-17] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor] Shard [6] located at [Actor[akka://PersistentFsmPoc/system/sharding/transaction-actor#769956182]]
[DEBUG] [03/28/2016 11:18:06.179] [PersistentFsmPoc-akka.actor.default-dispatcher-17] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor] Shard was initialized 6
[DEBUG] [03/28/2016 11:18:06.179] [PersistentFsmPoc-akka.actor.default-dispatcher-17] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor] Deliver [1] buffered messages for shard [6]
[DEBUG] [03/28/2016 11:18:06.180] [PersistentFsmPoc-akka.actor.default-dispatcher-2] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor/6] Starting entity [1021] in shard [6]
[INFO] [03/28/2016 11:18:06.185] [PersistentFsmPoc-akka.actor.default-dispatcher-17] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor/6/1021] SimpleTransactionActor started
[DEBUG] [03/28/2016 11:18:06.194] [PersistentFsmPoc-akka.actor.default-dispatcher-17] [akka://PersistentFsmPoc/system/cassandra-journal/StreamSupervisor-0/flow-1-1-asyncReplayMessages] unhandled message from Actor[akka://PersistentFsmPoc/deadLetters]: Request(16)
[INFO] [03/28/2016 11:18:06.292] [PersistentFsmPoc-akka.actor.default-dispatcher-25] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor/6/1021] Receive Recover called with message: PerformTransactionStart(1021)
[INFO] [03/28/2016 11:18:06.292] [PersistentFsmPoc-akka.actor.default-dispatcher-25] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor/6/1021] Receive Recover called with message: RecoveryCompleted
[INFO] [03/28/2016 11:18:06.292] [PersistentFsmPoc-akka.actor.default-dispatcher-25] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor/6/1021] RECEIVE CALLED with message ChangeTransactionData(1021,22222222)
[INFO] [03/28/2016 11:18:06.293] [PersistentFsmPoc-akka.actor.default-dispatcher-25] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor/6/1021] There are 1 data items within a transaction 1021
[DEBUG] [03/28/2016 11:18:06.357] [PersistentFsmPoc-akka.actor.default-dispatcher-4] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/user/IO-HTTP/listener-0/0] Connection was PeerClosed, awaiting TcpConnection termination...
[DEBUG] [03/28/2016 11:18:06.357] [PersistentFsmPoc-akka.actor.default-dispatcher-2] [akka://PersistentFsmPoc/user/$a] received unhandled message PeerClosed from Actor[akka://PersistentFsmPoc/user/IO-HTTP/listener-0/0#971793773]
```
... so here I receive next sequence of events, that is correct:
```
[akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor/6/1021] Receive Recover called with message: PerformTransactionStart(1021)
[INFO] [03/28/2016 11:18:06.292] [PersistentFsmPoc-akka.actor.default-dispatcher-25] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor/6/1021] Receive Recover called with message: RecoveryCompleted
```

then, when I switch to the cassandra of version 2.x, the log file looks like:
```
11:24:28.995 TKD [cluster1-nio-worker-2] DEBUG com.datastax.driver.core.Session - Added connection pool for /127.0.0.1:9042
[DEBUG] [03/28/2016 11:24:29.039] [PersistentFsmPoc-cassandra-snapshot-store.default-dispatcher-22] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/cassandra-snapshot-store] initialized CassandraSession successfully
[DEBUG] [03/28/2016 11:24:29.049] [PersistentFsmPoc-cassandra-journal.default-dispatcher-20] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/cassandra-journal] initialized CassandraSession successfully
[DEBUG] [03/28/2016 11:24:29.965] [PersistentFsmPoc-akka.actor.default-dispatcher-14] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actorCoordinator/singleton/coordinator] ShardRegion registered: [Actor[akka://PersistentFsmPoc/system/sharding/transaction-actor#-156410205]]
[DEBUG] [03/28/2016 11:24:29.973] [PersistentFsmPoc-cassandra-journal.default-dispatcher-20] [akka.serialization.Serialization(akka://PersistentFsmPoc)] Using serializer[akka.cluster.sharding.protobuf.ClusterShardingMessageSerializer] for message [akka.cluster.sharding.ShardCoordinator$Internal$ShardRegionRegistered]
[DEBUG] [03/28/2016 11:24:29.989] [PersistentFsmPoc-akka.actor.default-dispatcher-17] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor] Retry request for shard [6] homes from coordinator at [Actor[akka://PersistentFsmPoc/system/sharding/transaction-actorCoordinator/singleton/coordinator#-752337014]]. [1] buffered messages.
[DEBUG] [03/28/2016 11:24:29.992] [PersistentFsmPoc-cassandra-journal.default-dispatcher-25] [akka.serialization.Serialization(akka://PersistentFsmPoc)] Using serializer[akka.cluster.sharding.protobuf.ClusterShardingMessageSerializer] for message [akka.cluster.sharding.ShardCoordinator$Internal$ShardHomeAllocated]
[DEBUG] [03/28/2016 11:24:30.000] [PersistentFsmPoc-akka.actor.default-dispatcher-2] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actorCoordinator/singleton/coordinator] Shard [6] allocated at [Actor[akka://PersistentFsmPoc/system/sharding/transaction-actor#-156410205]]
[DEBUG] [03/28/2016 11:24:30.000] [PersistentFsmPoc-akka.actor.default-dispatcher-15] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor] Host Shard [6] 
[DEBUG] [03/28/2016 11:24:30.011] [PersistentFsmPoc-akka.actor.default-dispatcher-15] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor] Starting shard [6] in region
[DEBUG] [03/28/2016 11:24:30.016] [PersistentFsmPoc-akka.actor.default-dispatcher-15] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor] Shard [6] located at [Actor[akka://PersistentFsmPoc/system/sharding/transaction-actor#-156410205]]
[DEBUG] [03/28/2016 11:24:30.018] [PersistentFsmPoc-akka.actor.default-dispatcher-15] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor] Shard was initialized 6
[DEBUG] [03/28/2016 11:24:30.018] [PersistentFsmPoc-akka.actor.default-dispatcher-15] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor] Deliver [1] buffered messages for shard [6]
[DEBUG] [03/28/2016 11:24:30.019] [PersistentFsmPoc-akka.actor.default-dispatcher-19] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor/6] Starting entity [1021] in shard [6]
[INFO] [03/28/2016 11:24:30.027] [PersistentFsmPoc-akka.actor.default-dispatcher-2] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor/6/1021] SimpleTransactionActor started
[INFO] [03/28/2016 11:24:30.035] [PersistentFsmPoc-akka.actor.default-dispatcher-2] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor/6/1021] Receive Recover called with message: RecoveryCompleted
[INFO] [03/28/2016 11:24:30.036] [PersistentFsmPoc-akka.actor.default-dispatcher-2] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor/6/1021] RECEIVE CALLED with message ChangeTransactionData(1021,22222222)
[INFO] [03/28/2016 11:24:30.044] [PersistentFsmPoc-akka.actor.default-dispatcher-2] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor/6/1021] Unexpected event received: ChangeTransactionData(1021,22222222). Transaction is of UninitializedData()
```
... and the sequence of events is the next one:
```
[akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor/6/1021] SimpleTransactionActor started
[INFO] [03/28/2016 11:24:30.035] [PersistentFsmPoc-akka.actor.default-dispatcher-2] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor/6/1021] Receive Recover called with message: RecoveryCompleted
```
... that is not correct as I receive `RecoveryCompleted` immediately after the start of an actor.

For an easier look at the problem I've checked in my poc here https://github.com/mkhudyakov/poc-persistent-fsm and described the steps I perform in `README.md`

**Comment by mkhudyakov** [comment] 2016-03-28 08:50
And forgot to mention, no migration takes place in this test - the keyspace is the new one with no tables.

**Comment by patriknw** [comment] 2016-03-31 07:10
I will look into this, but the rest of this week is fully booked.

**Comment by mkhudyakov** [comment] 2016-03-31 13:39
Thank you very much, @patriknw, I've tried to play with other versions of cassandra - 4.8.3 & 4.8.4 - and I do get the expected behavior of `akka-persistence-cassandra` - the events are being replayed. So at this point the question is no more actual for me. However, the above mentioned issue seems to be there.

**Comment by patriknw** [comment] 2016-04-12 13:35
I have run all relevant tests with Cassandra 2.1.6 several times and no failures. I'm trying the linked project now.

**Comment by patriknw** [comment] 2016-04-12 13:52
I ran https://github.com/mkhudyakov/poc-persistent-fsm with Cassandra 2.1.6 without any problems (as far as I can see). The replayed events are before recover completed:

```
[INFO] [04/12/2016 15:47:22.716] [PersistentFsmPoc-akka.actor.default-dispatcher-18] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor/0/123] Receive Recover called with message: PerformTransactionStart(123)
[INFO] [04/12/2016 15:47:22.717] [PersistentFsmPoc-akka.actor.default-dispatcher-18] [akka.tcp://PersistentFsmPoc@127.0.0.1:2551/system/sharding/transaction-actor/0/123] Receive Recover called with message: RecoveryCompleted
```

**Comment by patriknw** [comment] 2016-04-18 06:20
Closing this, since I can't reproduce it. I suspect issues with the static column in 2.1.x versions of C*.

**Closed by patriknw** 2016-04-18 06:20 UTC

**Comment by mkhudyakov** [comment] 2016-04-19 08:07
Thank you, @patriknw, for your effort. As the upgrade of DSE to version 4.8.4 did help me, this problem is no more the problem. Thank you for fast feedback
