### ISSUE TITLE
Failure: CassandraJournalPerfSpec

### ISSUE THREAD

**Issue by raboof** [akka/akka-persistence-cassandra#229] opened 2017-09-04 13:21 UTC
```
- must measure: persist()-ing 10000 events *** FAILED *** (20 seconds, 11 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (20 seconds) during expectMsg while waiting for 10000
[info]   at scala.Predef$.assert(Predef.scala:219)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:386)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:372)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:372)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:831)
[info]   at akka.persistence.journal.JournalPerfSpec.feedAndExpectLast(JournalPerfSpec.scala:87)
[info]   at akka.persistence.journal.JournalPerfSpec.$anonfun$new$7(JournalPerfSpec.scala:136)
[info]   at akka.persistence.journal.JournalPerfSpec.measure(JournalPerfSpec.scala:97)
[info]   at akka.persistence.journal.JournalPerfSpec.$anonfun$new$5(JournalPerfSpec.scala:135)
```

**Comment by johanandren** [comment] 2017-11-21 15:37
https://travis-ci.org/akka/akka-persistence-cassandra/jobs/305301165

**Comment by chbatey** [comment] 2017-12-01 08:03
Closing as duplicate of #215

**Closed** 2017-12-01 08:03 UTC
Labels: failed
