### ISSUE TITLE
Investigate replacement for Materialized Views

### ISSUE THREAD

**Issue by ktoso** [akka/akka-persistence-cassandra#247] opened 2017-10-12 12:35 UTC
Brought up by @chbatey 

Materialized Views are not as reliable as one might think they are, and may even be retroactively be marked as experimental (!), thus we need to investigate a replacement for them.

Examples of issues: 

> Here are a few specifics:
> 
> * Casuing OOMs: https://issues.apache.org/jira/browse/CASSANDRA-12783
> * Incremental repair broken: https://issues.apache.org/jira/browse/CASSANDRA-12888
> * Breakages during node movements: https://issues.apache.org/jira/browse/CASSANDRA-13069
>

**Comment by patriknw** [comment] 2017-10-16 11:35
We had a design discussion about this and here are my notes (and some additional thoughts).

`messages` table: PRIMARY KEY ((persistence_id, partition_nr), sequence_nr, timestamp, timebucket))

`events_tag` table: PRIMARY KEY ((tag, timebucket), timestamp, persistence_id, partition_nr, sequence_nr)

After writing to the `messages` tables it will also write to the events_tag table. One row per tag. This can be done as write-behind or before completing the future of the persist call. Either way there is a (small) risk that the event was written to the `message` table but not to the `events_tag` table. It shouldn't be written to `events_tag` before or concurrent to the `messages` because having events in `events_tag` without having it in `messages` would be bad.

We need a way to copy such missing events to the `events_tag` table and also to be able to populate the table when migrating to this new solution or when rebuilding it for other reasons. That can be a background job that infrequently does:
* Find all persistenceId
* For each persistenceId find all events after an offset (seqNr)
* Upsert event to `events_tag` table (upsert will de-duplicate in case it was already in the table)

For finding all persistenceId the existing allPersistenceIds query should be changed, because the existing “select distinct” is too inefficient (full table scan). Instead there should be another table with all persistence ids. That can be written to when persisting events, and by caching (in memory) already used persistenceIds it only has to write to that table once per new persistenceId.

The offset can be written to a separate table in batches, because it is fine that this job process events more than once.

So far rather straightforward, but there is one more challenge. Current implementation has the limitation that all events from a persistenceId must be tagged to be able to ensure that all events are delivered, in right order. It’s using the sequence numbers to detect missing events, and if not all events are tagged it would be a valid gap in the sequence numbers.

Example:
* e-1 tagged a
* e-2 tagged b
* e-3 tagged a

When `eventsByTag(“a”)` is reading e3 it must know if seqNr 2 is missing because delayed due to eventual consistency or missing because it’s not tagged with a.

By writing/read `events_tag` with Quorum we get better guarantees than the eventual consistency of the materialized view. A question is what guarantees we have if e-2 and e-3 are stored in different `events_tag` partitions (different time buckets)? Is it guaranteed that e-2 is visible before e-3 if e-2 was tagged with a?

We would also have to make sure e-2 is actually written to `events_tag` before e-3. The problem could be if there is a crash after writing e-2 to messages but before writing e-2 to events_tag, and then e-3 is written to events_tag before e-2 was fixed by the background job.

One way might be to trigger the copy job for a persistenceId when there is a replay request. In that way we could ensure that e-2 is written to events_tag before e-3 also in this failure scenario. The question about the reads from different partitions must still be verified.

Another way might be that events are only copied to `events_tag` by the background job. The journal actor could trigger the background job for a persistenceId when writing events for a persistenceId. Think of the background job as a child actor for each persistenceId to the journal actor. When starting up it must read all events from the offset, but when the journal is writing it can write to `events_tag` without reading from `messages`. This also have the advantage that writes to `events_tag` can be batched by this actor, and it doesn't slow down the ordinary writes to `messages`.

A different solution would be to use a separate sequence number series for each tag. Then the query could detect missing sequence numbers. The difficulty with this solution is how to maintain the starting point of these sequence numbers when the journal actor is restarted. Where should it be stored?

**Comment by chbatey** [comment] 2017-10-16 12:03
A few questions that come to mind:
* Do we want to support both modes? If users haven't seen any issues with MVs should we force them to migrate? Also if MVs become stable we may way to go back? Or are the extra eventual consistency guarantees enough to justify always doing this manually?
* Do we need to offer near to no down time upgrade path? E.g. 
  * Migrate in background
  * Upgrade to a version that writes to MV and our new table
  * Upgrade to a version that reads the new table
  * Drop MV

> A question is what guarantees we have if e-2 and e-3 are stored in different events_tag partitions (different time buckets)? Is it guaranteed that e-2 is visible before e-3 if e-2 was tagged with a?

If the writes to the event_tag table are concurrent we would have no guarantees.

However if in our implementation, e-2 is acknowledged at `QUORUM` before we start writing e-3 we know that e-2 will be visible to any `QUORUM` reads anytime after e-3 has been written to Cassandra. So if we a query sees e-3 in the tag table and has done a `QUORUM` read on which ever partition e-2 is in we will definitely see e-2. The only guarantee we are relying on in Cassandra is that if a `QUORUM` write succeeds a subsequent read `we` can guarantee will happen after that success will see that value.

If in our implementation we do anything asynchronously for the tag table then we lose this guarantee.

> One way might be to trigger the copy job for a persistenceId when there is a replay request. In that way we could ensure that e-2 is written to events_tag before e-3 also in this failure scenario.

Good idea

**Comment by jypma** [comment] 2017-10-16 12:14
@patriknw Your suggestion is very similar to an implementation we'd done ourselves, before `akka-persistence-cassandra` had querying. I believe we actually _did_ write to the time bucket index first, since it's only an index, and not finding a message afterwards wouldn't be a big deal (you'd just forget about it). Of course you'd complete the future after both index and main store are complete.

We didn't have a clean solution for `timebucket` though, that fully accounted for clock drift across servers.

@chbatey raises valid migration questions; let's tackle those once a concrete implementation direction has formed.

**Comment by patriknw** [comment] 2017-10-16 12:21
One more note regarding deletes that I forgot. We should treat the `events_tag` as completely detached from deletes in `messages`.  We can use TTL with #235.

It's a lot simpler than trying to propagate deletes and also fits the typical use case of `events_tag`, which is to build up a read model in another DB or table that can serve end user queries.

**Comment by patriknw** [comment] 2017-10-16 12:23
> However if in our implementation, e-2 is acknowledged at QUORUM before we start writing e-3 we know that e-2 will be visible to any QUORUM reads anytime after e-3 has been written to Cassandra. 

That is great. I just wanted it to be confirmed one more time that it holds across different partitions.

**Comment by jypma** [comment] 2017-10-23 10:58
@ktoso Do you have a reference for _"may even be retroactively be marked as experimental"_? A quick google search didn't turn anything up...

**Comment by chbatey** [comment] 2017-10-23 11:07
@jypma here's the permalink to the discussion on the cassandra dev mailing list: https://lists.apache.org/thread.html/d81a61da48e1b872d7599df4edfa8e244d34cbd591a18539f724796f@%3Cdev.cassandra.apache.org%3E

**Closed** 2018-02-07 14:38 UTC
